services:
  frontend:
    build: frontend
    container_name: languasia-front
    depends_on:
      - proxy
      - app
    expose:
      - 1234
    networks:
      - languasia-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 15s

  app:
    build: backend
    container_name: languasia-app
    expose: 
      - 8080
    environment:
      DB_HOST: database
    networks:
      - languasia-network
    depends_on:
      - proxy
      - database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: postgres:16-alpine
    container_name: languasia-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: languasia
      POSTGRES_DB: languasia
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - languasia-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "languasia", "-U", "languasia"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 15s

  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: languasia-swagger-ui
    volumes:
      - ./backend/openapi.yml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    restart: unless-stopped
    networks:
      - languasia-network

  proxy:
    image: nginx:alpine
    container_name: languasia-proxy
    ports:
      - 443:443
      - 80:80
      - 67:67
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./loading:/var/www/html/loading:ro
    restart: unless-stopped
    networks:
      - languasia-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  languasia-network:
    driver: bridge

volumes:
  postgres_data:

