INSERT INTO hobbies (title) VALUES 
('sport'),
('math'),
('cycling'),
('chess'),
('drawing'),
('sculpturing'),
('programming'),
('cooking'),
('pets'),
('hiking'),
('running'),
('swimming'),
('yoga'),
('gardening'),
('photography'),
('fishing'),
('hunting'),
('archery'),
('golf'),
('tennis'),
('badminton'),
('table tennis'),
('squash'),
('baseball'),
('basketball'),
('volleyball'),
('soccer'),
('rugby'),
('cricket'),
('hockey'),
('ice hockey'),
('field hockey'),
('lacrosse'),
('karate'),
('judo'),
('taekwondo'),
('jiu-jitsu'),
('aikido'),
('kung fu'),
('boxing'),
('wrestling'),
('fencing'),
('gymnastics'),
('cheerleading'),
('dance'),
('ballet'),
('hip-hop dance'),
('salsa dancing'),
('ballroom dancing'),
('pilates'),
('weightlifting'),
('bodybuilding'),
('crossfit'),
('parkour'),
('trampolining'),
('horseback riding'),
('polo'),
('surfing'),
('skiing'),
('snowboarding'),
('skating'),
('skateboarding'),
('rollerblading'),
('kayaking'),
('canoeing'),
('rafting'),
('sailing'),
('windsurfing'),
('kitesurfing'),
('paragliding'),
('skydiving'),
('bungee jumping'),
('caving'),
('mountaineering'),
('rock climbing'),
('birdwatching'),
('stargazing'),
('camping'),
('backpacking'),
('geocaching'),
('foraging'),
('nature photography'),
('botany'),
('beekeeping'),
('farming'),
('pottery'),
('ceramics'),
('calligraphy'),
('knitting'),
('crocheting'),
('sewing'),
('quilting'),
('embroidery'),
('cross-stitch'),
('weaving'),
('macrame'),
('jewelry making'),
('woodworking'),
('carpentry'),
('metalworking'),
('blacksmithing'),
('glassblowing'),
('stained glass'),
('origami'),
('scrapbooking'),
('card making'),
('model building'),
('miniature painting'),
('doll making'),
('puppet making'),
('candle making'),
('soap making'),
('leatherworking'),
('bookbinding'),
('printmaking'),
('digital art'),
('graphic design'),
('animation'),
('filmmaking'),
('videography'),
('hobby horsing');
